# Generated by Django 2.0.3 on 2018-03-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=25)),
                ('u_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('account', models.IntegerField()),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('sqft', models.IntegerField()),
                ('num_bed', models.IntegerField()),
                ('num_bath', models.FloatField()),
                ('max_res', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruben.Unit'),
        ),
    ]
